version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    container_name: mk8dx_app
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mk8db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: