version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - MODE=development
      - FLASK_APP=app.py
      - FLASK_ENV=development
