"""Add screenshot_path and verified columns

Revision ID: 1b8f48b0fa2c
Revises: 293fd68e50e6
Create Date: 2025-10-05 15:33:13.963735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8f48b0fa2c'
down_revision = '293fd68e50e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaderboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('screenshot_path', sa.String(length=255),
        nullable=False, server_default='legacy'))
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True,
        server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaderboard', schema=None) as batch_op:
        batch_op.drop_column('verified')
        batch_op.drop_column('screenshot_path')

    # ### end Alembic commands ###
