"""removed name from leaderboard table

Revision ID: 293fd68e50e6
Revises: f08498122870
Create Date: 2025-08-29 01:21:15.236981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293fd68e50e6'
down_revision = 'f08498122870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaderboard', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaderboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
