"""add user_id to leaderboard

Revision ID: f08498122870
Revises: 6b305130b5f1
Create Date: 2025-08-28 21:48:50.621457

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f08498122870"
down_revision = "6b305130b5f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leaderboard", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, "user", ["user_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leaderboard", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
