"""initial migration

Revision ID: f758d8dd7154
Revises: 
Create Date: 2025-08-27 04:35:10.916269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f758d8dd7154'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('time_mins', sa.Integer(), nullable=False),
    sa.Column('time_s', sa.Integer(), nullable=False),
    sa.Column('time_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leaderboard')
    # ### end Alembic commands ###
