name: Publish Docker image

on:
  push:
    branches:
      - main   # runs only when you push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set version
        run: echo "VERSION=1.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: lucastidy/flask-mk8-leaderboard:${{ env.VERSION }}

      - name: Build and push Docker image (latest)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: lucastidy/flask-mk8-leaderboard:latest